### ISSUE TITLE
Is it possible to set the vehicle to drive forward only

### ISSUE THREAD

**Issue by polo1968** [RajPShinde/Hybrid-A-Star#1]
Thanks for your excellent work！i wonder if  it is possible to set the vehicle to drive forward only

**Comment by RajPShinde** [comment]
@polo1968 We can do that in the following two ways
1. Disable creating nodes that move the vehicle backwards & replace the Reeds-Shepp curves with Dubins curves.
2. Increase the cost for Backward Motion (This will only incentivize Forward Motions but wont guarantee that we have no Backward Motions).

**Comment by polo1968** [comment]
Sorry to see your reply just now. Your suggestions are&nbsp;very helpful. I will try it&nbsp;. Thank you so much!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RajPShinde/Hybrid-A-Star"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月13日(星期二) 晚上8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RajPShinde/Hybrid-A-Star] Is it possible to set the vehicle to drive forward only (Issue #1)





 
@polo1968 We can do that in the following two ways
  
Disable creating nodes that move the vehicle backwards &amp; replace the Reeds-Shepp curves with Dubins curves.
 
Increase the cost for Backward Motion (This will only incentivize Forward Motions but wont guarantee that we have no Backward Motions).
